### ISSUE TITLE
Get CL-REDDIT into the list of reddit API wrappers

### ISSUE THREAD

**Issue by flpa** [jperson/cl-reddit#6]
Hi,
when I heard about the Reddit API I consulted the list of wrappers at https://github.com/reddit/reddit/wiki/API-Wrappers and wondered why there's no CL implementation. I considered writing my own, but then I found this project, since I would have chosen the same name.
I think CL-REDDIT should be in that list - from what I can tell, it works pretty good. Of course there still are TODOs, but adding the project to the list might attract more contributors. I think I will contribute, once I'm familiar with the code.

What do you think?

**Comment by jperson** [comment]
Sounds good, I didn't know about the Reddit API list, added now.  All contributions are welcome!
